CREATE SEQUENCE customer_seq
START WITH 1001
INCREMENT BY 1;

CREATE SEQUENCE account_seq
START WITH 2001
INCREMENT BY 1;

CREATE SEQUENCE txn_seq_n
START WITH 3001
INCREMENT BY 1;

CREATE SEQUENCE loan_seq
START WITH 4001
INCREMENT BY 1;

CREATE SEQUENCE npa_seq
START WITH 5001
INCREMENT BY 1;

CREATE SEQUENCE audit_seq
START WITH 6001
INCREMENT BY 1;

CREATE SEQUENCE rate_seq
START WITH 7001
INCREMENT BY 1;

CREATE SEQUENCE interest_log_seq
START WITH 1
INCREMENT BY 1;
